post_install() {
	touch /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
	touch /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
	touch /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
	touch /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml


	# Set background
	xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/image-path -n -t string -s "/usr/share/backgrounds/manjaro-strit.jpg"
	CMD=`grep image-path /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep image-path /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	done

	# Set theme
	CMD=`grep image-path /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep image-path /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	done
	xfconf-query -c xsettings -p /Net/ThemeName -n -t string -s "Vertex-Maia-Dark"

	CMD=`grep ThemeName /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep ThemeName /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	done
	xfconf-query -c xfwm4 -p /general/theme -n -t string -s "Vertex-Maia-Dark"

	# Set icon theme
	CMD=`grep theme /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep theme /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	done
	xfconf-query -c xsettings -p /Net/IconThemeName -n -t string -s "maia"

	# Set compositor
	CMD=`grep IconThemeName /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep IconThemeName /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	done
	xfconf-query -c xfwm4 -p /general/show_frame_shadow -n -t bool -s "true"

	# Set workspaces count
	CMD=`grep show_frame_shadow /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep show_frame_shadow /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	done
	xfconf-query -c xfwm4 -p /general/workspace_count -n -t int -s 2

	# Set panels
	CMD=`grep workspace_count /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep workspace_count /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	done
	xfconf-query -c xfce4-panel -p /panels/panel-2/autohide -n -t bool -s "true"

	CMD=`grep autohide /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep autohide /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	done
	xfconf-query -c xfce4-panel -p /panels/panel-1/size -n -t int -s 25

	# Set menu logo
	CMD=`grep size /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep size /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	done
	xfconf-query -c xfce4-panel -p /plugins/plugin-1/button-icon -n -t string -s "/usr/share/antergos/antergos-menu.png"

}

post_upgrade() {
  post_install
}

post_remove() {

}